version: '3.1'

services:
  wakfu_redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  wakfu_postgresql:
    image: wakfu_postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_MASTER_PASSWORD}
      DB_WAKFU_PASSWORD: ${DB_WAKFU_PASSWORD}

  wakfu_app:
    image: node:latest
    restart: always
    ports:
      - 127.0.0.1:5001:5001
    command: bash -c "cd /home/wakfu-map/website; npm run start"
    volumes:
      - ..:/home/wakfu-map